### ISSUE TITLE
prediction from mnlm error

### ISSUE THREAD

**Issue by myeomans** [TaddyLab/textir#1] opened 2016-06-18 18:11 UTC
Hi Matt,

I've been using mnlm for a new text dataset and the predictions don't seem to be working. Here's an example that produces the same error as in my data...

library(textir)
data(we8there)
exes<-we8thereCounts
covars<-we8thereRatings
cl <- makeCluster(detectCores(), type="FORK")
inverse.reg<-mnlm(counts=exes, covars=covars, cl=cl)
PP<-predict(inverse.reg, newdata=exes,type="response")

The error I get is just from this matrix multiplication in predict.dmrcoef:
eta <- t(tcrossprod(t(object[-1,,drop=FALSE]),newdata) + object[1,])
"Cholmod error 'A and B inner dimensions must match' at file ../MatrixOps/cholmod_ssmult.c, line 82"

It works fine with the Cushings and fgl example data, and I've tried monkeying around, but I can't figure out the general solution. Am I just using this wrong or is there a deeper issue?

Any help would be appreciated! I have a dataset that's just begging for a multinomial inverse regression, and the coefficients from the projection functions are already fascinating. But I want to validate the model out-of-sample and this particular error is holding me back.

Thanks!

**Comment by mataddy** [comment] 2016-06-19 09:53
thanks @myeomans I'm traveling but on a quick look I think that the issue is that you want to have newdata=covars for the predict function.  Here 'response' are word counts, so in your code you are trying to predict word counts from word counts (i.e. y from y).  I'll close this but feel free to reopen if I have it confused.

**Closed as completed by mataddy** 2016-06-19 09:53 UTC

**Comment by myeomans** [comment] 2016-06-19 11:29
OK, I got it. The code runs now, though I want to predict from text (not the other way around), so I need to rethink the problem.

Anyways, thanks for the quick response!

**Comment by mataddy** [comment] 2016-06-19 11:44
for that, see the other options for prediction 'type'.  also, I think I do this in the congress109 examples
